[package]
name = "rustbik"
version = "0.1.0"
authors = ["Lampij <ben.david.pinter@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.0.5"
